### ISSUE TITLE
open-webui-3.3.0 helm chart contains the old version of the open-webui

### ISSUE THREAD

**Issue by muhyid** [open-webui/helm-charts#91]
Dear Open-WebUI Team,
I have just reviewed the open-webui-3.3.0 helm chart, it uses open-webui version 0.3.24 instead of 0.3.30. Also, I couldn't see the configmap for Open-webui-env, environment values are added under StatefullSet again, ConfigMap was included with version 3.2.0.
Are these normal?

**Comment by bergutman** [comment]
Regarding v0.3.24 > 0.3.30 I will submit a PR shortly

**Comment by nwhobart** [comment]
@bergutman is this currently a manual process? I noticed that the helm chart version doesn't necessarily get bumped with app version updates. Is this a conscious decision or it some automation planned in the future so the Helm chart version doesn't fall too far behind the app version?

**Comment by bergutman** [comment]
I'm not an official contributor or anything, so I cannot comment on design decisions. However, yes, it is currently a manual process. I suspect this approach is in place to ensure that new versions don't break things. Additionally, new releases often come in bursts so it's sometimes helpful to hold off for a bit. I happen to host my own OWUI instance on a production Kubernetes cluster, so occasionally I'll be able to test a new version before @0xThresh in which case I'll submit a quick PR if there's no issues. Hopefully they don't find this behavior pesky. I haven't actually ever bothered to asked them, lol!

**Comment by nwhobart** [comment]
> I'm not an official contributor or anything, so I cannot comment on design decisions. However, yes, it is currently a manual process. I suspect this approach is in place to ensure that new versions don't break things. Additionally, new releases often come in bursts so it's sometimes helpful to hold off for a bit. I happen to host my own OWUI instance on a production Kubernetes cluster, so occasionally I'll be able to test a new version before @0xThresh in which case I'll submit a quick PR if there's no issues. Hopefully they don't find this behavior pesky. I haven't actually ever bothered to asked them, lol!

Thanks for your efforts. I and my company are new to using OWUI and I'll help when I can. We're running in as "production" in a tools k8s cluster auto-managed by a Flux resource. Appreciate the response.

**Comment by 0xThresh** [comment]
> Dear Open-WebUI Team, I have just reviewed the open-webui-3.3.0 helm chart, it uses open-webui version 0.3.24 instead of 0.3.30. Also, I couldn't see the configmap for Open-webui-env, environment values are added under StatefullSet again, ConfigMap was included with version 3.2.0. Are these normal?

Hi @muhyid, apologies for the delays on the new versions, I try to keep up as much as I can. Community PRs help keep it up to date when I fall behind, I'm quick to merge PRs that only upgrade versions! As for the ConfigMap, there was an issue with secrets defined through `extraEnvVars` that I did not consider when making that change. We need to go back to the drawing board on that implementation, but that's why 3.3.x is back to not using a ConfigMap. 

> bergutman is this currently a manual process? I noticed that the helm chart version doesn't necessarily get bumped with app version updates. Is this a conscious decision or it some automation planned in the future so the Helm chart version doesn't fall too far behind the app version?

@nwhobart it's crossed my mind to update this automatically through Github Actions to avoid people needing to do that manually when submitting PRs, but I haven't had the time to look into what the implementation of that would look like. That would be another welcome PR if it's something you wanted to try to bring in. 


> I'm not an official contributor or anything, so I cannot comment on design decisions. However, yes, it is currently a manual process. I suspect this approach is in place to ensure that new versions don't break things. Additionally, new releases often come in bursts so it's sometimes helpful to hold off for a bit. I happen to host my own OWUI instance on a production Kubernetes cluster, so occasionally I'll be able to test a new version before @0xThresh in which case I'll submit a quick PR if there's no issues. Hopefully they don't find this behavior pesky. I haven't actually ever bothered to asked them, lol!

@bergutman your efforts are definitely appreciated! Anyone is welcome to tag me anytime on this repo, and I'll always get to it as quick as I can 😄
